zsh: add command-not-found handler for nix autoinstalling

diff --git a/cfgs/zshrc b/cfgs/zshrc
--- a/cfgs/zshrc
+++ b/cfgs/zshrc
@@ -104,3 +104,24 @@ test -e ~/.zshrc.local && source ~/.zshrc.local
 if [ "$TERM" = "dumb" ]; then
     PS1="> "
 fi
+
+
+if [ -n "$PS1" ]; then
+  # This function is called whenever a command is not found.
+command_not_found_handler() {
+  local p=/run/current-system/sw/bin/command-not-found
+  if [ -x $p -a -f /nix/var/nix/profiles/per-user/root/channels/nixos/programs.sqlite ]; then
+    # Run the helper program.
+    NIX_AUTO_RUN=true $p "$@"
+    # Retry the command if we just installed it.
+    if [ $? = 126 ]; then
+      "$@"
+    else
+      return 127
+    fi
+  else
+    echo "$1: command not found" >&2
+    return 127
+  fi
+}
+fi
